/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLiabilitiesImport } from './routes/_authenticated/liabilities'
import { Route as AuthenticatedCreateLiabilitiesImport } from './routes/_authenticated/create-liabilities'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedLiabilitiesRoute = AuthenticatedLiabilitiesImport.update({
  path: '/liabilities',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCreateLiabilitiesRoute =
  AuthenticatedCreateLiabilitiesImport.update({
    path: '/create-liabilities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/create-liabilities': {
      id: '/_authenticated/create-liabilities'
      path: '/create-liabilities'
      fullPath: '/create-liabilities'
      preLoaderRoute: typeof AuthenticatedCreateLiabilitiesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/liabilities': {
      id: '/_authenticated/liabilities'
      path: '/liabilities'
      fullPath: '/liabilities'
      preLoaderRoute: typeof AuthenticatedLiabilitiesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedCreateLiabilitiesRoute,
    AuthenticatedLiabilitiesRoute,
    AuthenticatedProfileRoute,
  }),
  AboutRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/create-liabilities",
        "/_authenticated/liabilities",
        "/_authenticated/profile"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_authenticated/create-liabilities": {
      "filePath": "_authenticated/create-liabilities.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/liabilities": {
      "filePath": "_authenticated/liabilities.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
