/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as LiabilitiesIdImport } from './routes/liabilities.$id'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLiabilitiesImport } from './routes/_authenticated/liabilities'
import { Route as AuthenticatedCreateLiabilitiesImport } from './routes/_authenticated/create-liabilities'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LiabilitiesIdRoute = LiabilitiesIdImport.update({
  path: '/liabilities/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedLiabilitiesRoute = AuthenticatedLiabilitiesImport.update({
  path: '/liabilities',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCreateLiabilitiesRoute =
  AuthenticatedCreateLiabilitiesImport.update({
    path: '/create-liabilities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/create-liabilities': {
      id: '/_authenticated/create-liabilities'
      path: '/create-liabilities'
      fullPath: '/create-liabilities'
      preLoaderRoute: typeof AuthenticatedCreateLiabilitiesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/liabilities': {
      id: '/_authenticated/liabilities'
      path: '/liabilities'
      fullPath: '/liabilities'
      preLoaderRoute: typeof AuthenticatedLiabilitiesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/liabilities/$id': {
      id: '/liabilities/$id'
      path: '/liabilities/$id'
      fullPath: '/liabilities/$id'
      preLoaderRoute: typeof LiabilitiesIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedCreateLiabilitiesRoute: typeof AuthenticatedCreateLiabilitiesRoute
  AuthenticatedLiabilitiesRoute: typeof AuthenticatedLiabilitiesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCreateLiabilitiesRoute: AuthenticatedCreateLiabilitiesRoute,
  AuthenticatedLiabilitiesRoute: AuthenticatedLiabilitiesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/create-liabilities': typeof AuthenticatedCreateLiabilitiesRoute
  '/liabilities': typeof AuthenticatedLiabilitiesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/liabilities/$id': typeof LiabilitiesIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/create-liabilities': typeof AuthenticatedCreateLiabilitiesRoute
  '/liabilities': typeof AuthenticatedLiabilitiesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/liabilities/$id': typeof LiabilitiesIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/_authenticated/create-liabilities': typeof AuthenticatedCreateLiabilitiesRoute
  '/_authenticated/liabilities': typeof AuthenticatedLiabilitiesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/liabilities/$id': typeof LiabilitiesIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/create-liabilities'
    | '/liabilities'
    | '/profile'
    | '/liabilities/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/create-liabilities'
    | '/liabilities'
    | '/profile'
    | '/liabilities/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/_authenticated/create-liabilities'
    | '/_authenticated/liabilities'
    | '/_authenticated/profile'
    | '/liabilities/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LiabilitiesIdRoute: typeof LiabilitiesIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LiabilitiesIdRoute: LiabilitiesIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/about",
        "/liabilities/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/create-liabilities",
        "/_authenticated/liabilities",
        "/_authenticated/profile"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_authenticated/create-liabilities": {
      "filePath": "_authenticated/create-liabilities.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/liabilities": {
      "filePath": "_authenticated/liabilities.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/liabilities/$id": {
      "filePath": "liabilities.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
